version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

