services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./startup.sh:/docker-entrypoint.d/startup.sh
      - ${HTTPS_CERT_PATH}:/certs/cert.crt
      - ${HTTPS_KEY_PATH}:/certs/cert.key
    environment:
      - DESTINATION_HTTP_PORT=${DESTINATION_HTTP_PORT}
      - DESTINATION_HTTPS_PORT=${DESTINATION_HTTPS_PORT}
      - HTTPS_DOMAIN=${HTTPS_DOMAIN}
