version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./startup.sh:/docker-entrypoint.d/startup.sh
    restart: always
    environment:
      - DESTINATION_HTTP_PORT=${DESTINATION_HTTP_PORT}

