version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    network_mode: host
    ports:
      - "${DESTINATION_HTTP_PORT_FOR}:80"
      - "${DESTINATION_HTTPS_PORT_FOR}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

